# Generated by Django 6.0.4 on 2026-04-13 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_self_follows(apps, schema_editor):
    Follow = apps.get_model('blogs', 'Follow')
    Follow.objects.filter(follower_id=models.F('following_id')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_tag_blog_reading_time_blog_tags_bookmark_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(delete_self_follows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
