# Generated by Codex on 2026-04-13

from django.conf import settings
from django.db import migrations


def create_existing_user_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    UserProfile = apps.get_model('blogs', 'UserProfile')
    existing_profile_user_ids = set(UserProfile.objects.values_list('user_id', flat=True))

    profiles = [
        UserProfile(user_id=user_id)
        for user_id in User.objects.values_list('id', flat=True)
        if user_id not in existing_profile_user_ids
    ]
    UserProfile.objects.bulk_create(profiles, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_userprofile_follow_prevent_self_follow_and_more'),
    ]

    operations = [
        migrations.RunPython(create_existing_user_profiles, migrations.RunPython.noop),
    ]
