# Generated by Django 6.0.6 on 2026-06-17 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_create_existing_user_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ai_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ai_verdict',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Review', 'Pending Review'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
