# Generated by Django 6.0.6 on 2026-06-18 19:11

from django.db import migrations, models


def copy_follow_requests_to_pending_follows(apps, schema_editor):
    Follow = apps.get_model('blogs', 'Follow')
    FollowRequest = apps.get_model('blogs', 'FollowRequest')

    for request in FollowRequest.objects.all():
        Follow.objects.get_or_create(
            follower_id=request.requester_id,
            following_id=request.target_id,
            defaults={
                'status': 'pending',
                'created_at': request.created_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_userprofile_is_private_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='accepted', max_length=10),
        ),
        migrations.RunPython(copy_follow_requests_to_pending_follows, migrations.RunPython.noop),
    ]
