# Generated by Django 6.0.6 on 2026-06-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('grammar_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vocabulary_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grammar_errors', models.JSONField(blank=True, default=list)),
                ('spelling_errors', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('ai_generated_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('quality_model', models.CharField(blank=True, max_length=150)),
                ('detector_model', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_analysis', to='blogs.blog')),
            ],
            options={
                'verbose_name_plural': 'blog content analyses',
            },
        ),
    ]
